services:
  retirement-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: blk-hacking-ind-ram-n
    ports:
      - "5477:5477"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
